### ISSUE TITLE
Running the beautifier on php files

### ISSUE THREAD

**Issue by ichiriac** [wmhilton/beautify#1]
Hi @wmhilton,

I would like to use the beautifier in order to fix indent on various PHP files. Is there option in order to process them from the CLI ?

BTW, here undocumented options passed as 2nd argument on php-unparser :

```js
{
  indent:  '    ', // 2 spaces indent
  dontUseWhitespaces: false, // if true, adds extra white space arround parenthesis,
  shortArray: false, // force to convert array() to []
  forceNamespaceBrackets: false // force to use namespaces with brackets (usefull when you want to concat every php file into a single one)
}
```

**Comment by billiegoose** [comment]
I see I forgot to document the --php option in the readme. It might work though...
Well, the CLI worked on .php files the last time I tried it! But it did not understand HTML inside PHP which was a big problem.

Try just running it, like `beautify *.php` and do let me know if it works or not. I'll be a lot more motivated to work on this project if I know people who are interested in using it!

**Comment by billiegoose** [comment]
I mean, I'm motivated to work on all my projects. But I'll prioritize projects if people are actively using them!

**Comment by ichiriac** [comment]
Hi William,

I've tried and no changes, and there is no output.  It would be great to tell with an option if I want tabs or spaces, and also space count, something like this :

```sh
beautify --spaces=2 *.php
beautify --tabs *.php
beautify --namespace *.php   # would force to encapsulate classes into a namespace closure
```

---

Another feature that I would need is to bundle files into a single file in order to ship them more easily. 

That would remove comments, remove spaces, and put namespaces code in bracket form (but it's the contrary to beautyfing)

```
beautify --bundle=dist.php *.php
```

**Comment by billiegoose** [comment]
Ah! I haven't *published* the version that does PHP. There must be something seriously disappointing about it... or maybe I left on a trip and forgot? (What was I doing 6 months ago?) Anyway: try installing it from Github:

```bash
git clone https://github.com/wmhilton/beautify
cd beautify
npm link
```

*That* version does something to .php files. I tried running it on a really janky project... it looks like it errored on half of them... a mix of `Unknown word`, `Cannot read property 'length' of null`, `Cannot ready property 'map' of undefined`. and one `Unexpected token`. So... definitely not ready for prime time. But if you're talking about concatenating PHP files then I bet your project files are a lot less janky than my test files. Give it a go!

**Comment by billiegoose** [comment]
> Another feature that I would need is to bundle files into a single file in order to ship them more easily.
>
> That would remove comments, remove spaces, and put namespaces code in bracket form (but it's the contrary to beautyfing)

Correct... I think those are good features but `beautify` is the wrong tool to put them in. It's just a thin shell over `php-unparser` which is where the magic happens. I think to properly minify/bundle PHP we'd want to modify or fork `php-unparser`. It would be nice if there was also an anti-beautify, that could compress and bundle HTML/CSS/JS/PHP. Maybe `productionizer` or `bundlify` something.... Or even better just get Webpack to support PHP! 😁

**Comment by ichiriac** [comment]
Hi @wmhilton, 

Actually you are using a really old and buggy version of php-unparser (and php-parser) they were both released some month ago, so I've removed the `lib` folder in order to use them - see actual PR.

Need to add fixes on php-unparser, still some little bugs, but it's working on 99% cases. I'll open separate issues in order to ask some features.
